# Generated by Django 6.0.2 on 2026-04-03 07:25

import django.utils.timezone
import expense_tracker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='from')),
                ('to', models.DateTimeField(verbose_name='to')),
                ('total_amount', models.FloatField(validators=[expense_tracker.validators.number_lt_zero])),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
                ('amount', models.FloatField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='expenses')),
            ],
            options={
                'ordering': ('-added_at',),
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-added_at',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250, null=True)),
                ('is_secure', models.BooleanField(default=True)),
            ],
        ),
    ]
